
bj_PI = 3.14159 ---@type number real constant
bj_E = 2.71828 ---@type number real constant
bj_CELLWIDTH = 128.0 ---@type number real constant
bj_CLIFFHEIGHT = 128.0 ---@type number real constant
bj_UNIT_FACING = 270.0 ---@type number real constant
bj_RADTODEG = 180.0 / bj_PI ---@type number real constant
bj_DEGTORAD = bj_PI / 180.0 ---@type number real constant
bj_TEXT_DELAY_QUEST = 20.00 ---@type number real constant
bj_TEXT_DELAY_QUESTUPDATE = 20.00 ---@type number real constant
bj_TEXT_DELAY_QUESTDONE = 20.00 ---@type number real constant
bj_TEXT_DELAY_QUESTFAILED = 20.00 ---@type number real constant
bj_TEXT_DELAY_QUESTREQUIREMENT = 20.00 ---@type number real constant
bj_TEXT_DELAY_MISSIONFAILED = 20.00 ---@type number real constant
bj_TEXT_DELAY_ALWAYSHINT = 12.00 ---@type number real constant
bj_TEXT_DELAY_HINT = 12.00 ---@type number real constant
bj_TEXT_DELAY_SECRET = 10.00 ---@type number real constant
bj_TEXT_DELAY_UNITACQUIRED = 15.00 ---@type number real constant
bj_TEXT_DELAY_UNITAVAILABLE = 10.00 ---@type number real constant
bj_TEXT_DELAY_ITEMACQUIRED = 10.00 ---@type number real constant
bj_TEXT_DELAY_WARNING = 12.00 ---@type number real constant
bj_QUEUE_DELAY_QUEST = 5.00 ---@type number real constant
bj_QUEUE_DELAY_HINT = 5.00 ---@type number real constant
bj_QUEUE_DELAY_SECRET = 3.00 ---@type number real constant
bj_HANDICAP_EASY = 60.00 ---@type number real constant
bj_GAME_STARTED_THRESHOLD = 0.01 ---@type number real constant
bj_WAIT_FOR_COND_MIN_INTERVAL = 0.10 ---@type number real constant
bj_POLLED_WAIT_INTERVAL = 0.10 ---@type number real constant
bj_POLLED_WAIT_SKIP_THRESHOLD = 2.00 ---@type number real constant
bj_MAX_INVENTORY = 6 ---@type number integer constant
bj_MAX_PLAYERS = 12 ---@type number integer constant
bj_PLAYER_NEUTRAL_VICTIM = 13 ---@type number integer constant
bj_PLAYER_NEUTRAL_EXTRA = 14 ---@type number integer constant
bj_MAX_PLAYER_SLOTS = 16 ---@type number integer constant
bj_MAX_SKELETONS = 25 ---@type number integer constant
bj_MAX_STOCK_ITEM_SLOTS = 11 ---@type number integer constant
bj_MAX_STOCK_UNIT_SLOTS = 11 ---@type number integer constant
bj_MAX_ITEM_LEVEL = 10 ---@type number integer constant
bj_TOD_DAWN = 6.00 ---@type number real constant
bj_TOD_DUSK = 18.00 ---@type number real constant
bj_MELEE_STARTING_TOD = 8.00 ---@type number real constant
bj_MELEE_STARTING_GOLD_V0 = 750 ---@type number integer constant
bj_MELEE_STARTING_GOLD_V1 = 500 ---@type number integer constant
bj_MELEE_STARTING_LUMBER_V0 = 200 ---@type number integer constant
bj_MELEE_STARTING_LUMBER_V1 = 150 ---@type number integer constant
bj_MELEE_STARTING_HERO_TOKENS = 1 ---@type number integer constant
bj_MELEE_HERO_LIMIT = 3 ---@type number integer constant
bj_MELEE_HERO_TYPE_LIMIT = 1 ---@type number integer constant
bj_MELEE_MINE_SEARCH_RADIUS = 2000 ---@type number real constant
bj_MELEE_CLEAR_UNITS_RADIUS = 1500 ---@type number real constant
bj_MELEE_CRIPPLE_TIMEOUT = 120.00 ---@type number real constant
bj_MELEE_CRIPPLE_MSG_DURATION = 20.00 ---@type number real constant
bj_MELEE_MAX_TWINKED_HEROES_V0 = 3 ---@type number integer constant
bj_MELEE_MAX_TWINKED_HEROES_V1 = 1 ---@type number integer constant
bj_CREEP_ITEM_DELAY = 0.50 ---@type number real constant
bj_STOCK_RESTOCK_INITIAL_DELAY = 120 ---@type number real constant
bj_STOCK_RESTOCK_INTERVAL = 30 ---@type number real constant
bj_STOCK_MAX_ITERATIONS = 20 ---@type number integer constant
bj_MAX_DEST_IN_REGION_EVENTS = 64 ---@type number integer constant
bj_CAMERA_MIN_FARZ = 100 ---@type number integer constant
bj_CAMERA_DEFAULT_DISTANCE = 1650 ---@type number integer constant
bj_CAMERA_DEFAULT_FARZ = 5000 ---@type number integer constant
bj_CAMERA_DEFAULT_AOA = 304 ---@type number integer constant
bj_CAMERA_DEFAULT_FOV = 70 ---@type number integer constant
bj_CAMERA_DEFAULT_ROLL = 0 ---@type number integer constant
bj_CAMERA_DEFAULT_ROTATION = 90 ---@type number integer constant
bj_RESCUE_PING_TIME = 2.00 ---@type number real constant
bj_NOTHING_SOUND_DURATION = 5.00 ---@type number real constant
bj_TRANSMISSION_PING_TIME = 1.00 ---@type number real constant
bj_TRANSMISSION_IND_RED = 255 ---@type number integer constant
bj_TRANSMISSION_IND_BLUE = 255 ---@type number integer constant
bj_TRANSMISSION_IND_GREEN = 255 ---@type number integer constant
bj_TRANSMISSION_IND_ALPHA = 255 ---@type number integer constant
bj_TRANSMISSION_PORT_HANGTIME = 1.50 ---@type number real constant
bj_CINEMODE_INTERFACEFADE = 0.50 ---@type number real constant
bj_CINEMODE_GAMESPEED = MAP_SPEED_NORMAL ---@type gamespeed constant
bj_CINEMODE_VOLUME_UNITMOVEMENT = 0.40 ---@type number real constant
bj_CINEMODE_VOLUME_UNITSOUNDS = 0.00 ---@type number real constant
bj_CINEMODE_VOLUME_COMBAT = 0.40 ---@type number real constant
bj_CINEMODE_VOLUME_SPELLS = 0.40 ---@type number real constant
bj_CINEMODE_VOLUME_UI = 0.00 ---@type number real constant
bj_CINEMODE_VOLUME_MUSIC = 0.55 ---@type number real constant
bj_CINEMODE_VOLUME_AMBIENTSOUNDS = 1.00 ---@type number real constant
bj_CINEMODE_VOLUME_FIRE = 0.60 ---@type number real constant
bj_SPEECH_VOLUME_UNITMOVEMENT = 0.25 ---@type number real constant
bj_SPEECH_VOLUME_UNITSOUNDS = 0.00 ---@type number real constant
bj_SPEECH_VOLUME_COMBAT = 0.25 ---@type number real constant
bj_SPEECH_VOLUME_SPELLS = 0.25 ---@type number real constant
bj_SPEECH_VOLUME_UI = 0.00 ---@type number real constant
bj_SPEECH_VOLUME_MUSIC = 0.55 ---@type number real constant
bj_SPEECH_VOLUME_AMBIENTSOUNDS = 1.00 ---@type number real constant
bj_SPEECH_VOLUME_FIRE = 0.60 ---@type number real constant
bj_SMARTPAN_TRESHOLD_PAN = 500 ---@type number real constant
bj_SMARTPAN_TRESHOLD_SNAP = 3500 ---@type number real constant
bj_MAX_QUEUED_TRIGGERS = 100 ---@type number integer constant
bj_QUEUED_TRIGGER_TIMEOUT = 180.00 ---@type number real constant
bj_CAMPAIGN_INDEX_T = 0 ---@type number integer constant
bj_CAMPAIGN_INDEX_H = 1 ---@type number integer constant
bj_CAMPAIGN_INDEX_U = 2 ---@type number integer constant
bj_CAMPAIGN_INDEX_O = 3 ---@type number integer constant
bj_CAMPAIGN_INDEX_N = 4 ---@type number integer constant
bj_CAMPAIGN_INDEX_XN = 5 ---@type number integer constant
bj_CAMPAIGN_INDEX_XH = 6 ---@type number integer constant
bj_CAMPAIGN_INDEX_XU = 7 ---@type number integer constant
bj_CAMPAIGN_INDEX_XO = 8 ---@type number integer constant
bj_CAMPAIGN_OFFSET_T = 0 ---@type number integer constant
bj_CAMPAIGN_OFFSET_H = 1 ---@type number integer constant
bj_CAMPAIGN_OFFSET_U = 2 ---@type number integer constant
bj_CAMPAIGN_OFFSET_O = 3 ---@type number integer constant
bj_CAMPAIGN_OFFSET_N = 4 ---@type number integer constant
bj_CAMPAIGN_OFFSET_XN = 0 ---@type number integer constant
bj_CAMPAIGN_OFFSET_XH = 1 ---@type number integer constant
bj_CAMPAIGN_OFFSET_XU = 2 ---@type number integer constant
bj_CAMPAIGN_OFFSET_XO = 3 ---@type number integer constant
bj_MISSION_INDEX_T00 = bj_CAMPAIGN_OFFSET_T * 1000 + 0 ---@type number integer constant
bj_MISSION_INDEX_T01 = bj_CAMPAIGN_OFFSET_T * 1000 + 1 ---@type number integer constant
bj_MISSION_INDEX_H00 = bj_CAMPAIGN_OFFSET_H * 1000 + 0 ---@type number integer constant
bj_MISSION_INDEX_H01 = bj_CAMPAIGN_OFFSET_H * 1000 + 1 ---@type number integer constant
bj_MISSION_INDEX_H02 = bj_CAMPAIGN_OFFSET_H * 1000 + 2 ---@type number integer constant
bj_MISSION_INDEX_H03 = bj_CAMPAIGN_OFFSET_H * 1000 + 3 ---@type number integer constant
bj_MISSION_INDEX_H04 = bj_CAMPAIGN_OFFSET_H * 1000 + 4 ---@type number integer constant
bj_MISSION_INDEX_H05 = bj_CAMPAIGN_OFFSET_H * 1000 + 5 ---@type number integer constant
bj_MISSION_INDEX_H06 = bj_CAMPAIGN_OFFSET_H * 1000 + 6 ---@type number integer constant
bj_MISSION_INDEX_H07 = bj_CAMPAIGN_OFFSET_H * 1000 + 7 ---@type number integer constant
bj_MISSION_INDEX_H08 = bj_CAMPAIGN_OFFSET_H * 1000 + 8 ---@type number integer constant
bj_MISSION_INDEX_H09 = bj_CAMPAIGN_OFFSET_H * 1000 + 9 ---@type number integer constant
bj_MISSION_INDEX_H10 = bj_CAMPAIGN_OFFSET_H * 1000 + 10 ---@type number integer constant
bj_MISSION_INDEX_H11 = bj_CAMPAIGN_OFFSET_H * 1000 + 11 ---@type number integer constant
bj_MISSION_INDEX_U00 = bj_CAMPAIGN_OFFSET_U * 1000 + 0 ---@type number integer constant
bj_MISSION_INDEX_U01 = bj_CAMPAIGN_OFFSET_U * 1000 + 1 ---@type number integer constant
bj_MISSION_INDEX_U02 = bj_CAMPAIGN_OFFSET_U * 1000 + 2 ---@type number integer constant
bj_MISSION_INDEX_U03 = bj_CAMPAIGN_OFFSET_U * 1000 + 3 ---@type number integer constant
bj_MISSION_INDEX_U05 = bj_CAMPAIGN_OFFSET_U * 1000 + 4 ---@type number integer constant
bj_MISSION_INDEX_U07 = bj_CAMPAIGN_OFFSET_U * 1000 + 5 ---@type number integer constant
bj_MISSION_INDEX_U08 = bj_CAMPAIGN_OFFSET_U * 1000 + 6 ---@type number integer constant
bj_MISSION_INDEX_U09 = bj_CAMPAIGN_OFFSET_U * 1000 + 7 ---@type number integer constant
bj_MISSION_INDEX_U10 = bj_CAMPAIGN_OFFSET_U * 1000 + 8 ---@type number integer constant
bj_MISSION_INDEX_U11 = bj_CAMPAIGN_OFFSET_U * 1000 + 9 ---@type number integer constant
bj_MISSION_INDEX_O00 = bj_CAMPAIGN_OFFSET_O * 1000 + 0 ---@type number integer constant
bj_MISSION_INDEX_O01 = bj_CAMPAIGN_OFFSET_O * 1000 + 1 ---@type number integer constant
bj_MISSION_INDEX_O02 = bj_CAMPAIGN_OFFSET_O * 1000 + 2 ---@type number integer constant
bj_MISSION_INDEX_O03 = bj_CAMPAIGN_OFFSET_O * 1000 + 3 ---@type number integer constant
bj_MISSION_INDEX_O04 = bj_CAMPAIGN_OFFSET_O * 1000 + 4 ---@type number integer constant
bj_MISSION_INDEX_O05 = bj_CAMPAIGN_OFFSET_O * 1000 + 5 ---@type number integer constant
bj_MISSION_INDEX_O06 = bj_CAMPAIGN_OFFSET_O * 1000 + 6 ---@type number integer constant
bj_MISSION_INDEX_O07 = bj_CAMPAIGN_OFFSET_O * 1000 + 7 ---@type number integer constant
bj_MISSION_INDEX_O08 = bj_CAMPAIGN_OFFSET_O * 1000 + 8 ---@type number integer constant
bj_MISSION_INDEX_O09 = bj_CAMPAIGN_OFFSET_O * 1000 + 9 ---@type number integer constant
bj_MISSION_INDEX_O10 = bj_CAMPAIGN_OFFSET_O * 1000 + 10 ---@type number integer constant
bj_MISSION_INDEX_N00 = bj_CAMPAIGN_OFFSET_N * 1000 + 0 ---@type number integer constant
bj_MISSION_INDEX_N01 = bj_CAMPAIGN_OFFSET_N * 1000 + 1 ---@type number integer constant
bj_MISSION_INDEX_N02 = bj_CAMPAIGN_OFFSET_N * 1000 + 2 ---@type number integer constant
bj_MISSION_INDEX_N03 = bj_CAMPAIGN_OFFSET_N * 1000 + 3 ---@type number integer constant
bj_MISSION_INDEX_N04 = bj_CAMPAIGN_OFFSET_N * 1000 + 4 ---@type number integer constant
bj_MISSION_INDEX_N05 = bj_CAMPAIGN_OFFSET_N * 1000 + 5 ---@type number integer constant
bj_MISSION_INDEX_N06 = bj_CAMPAIGN_OFFSET_N * 1000 + 6 ---@type number integer constant
bj_MISSION_INDEX_N07 = bj_CAMPAIGN_OFFSET_N * 1000 + 7 ---@type number integer constant
bj_MISSION_INDEX_N08 = bj_CAMPAIGN_OFFSET_N * 1000 + 8 ---@type number integer constant
bj_MISSION_INDEX_N09 = bj_CAMPAIGN_OFFSET_N * 1000 + 9 ---@type number integer constant
bj_MISSION_INDEX_XN00 = bj_CAMPAIGN_OFFSET_XN * 1000 + 0 ---@type number integer constant
bj_MISSION_INDEX_XN01 = bj_CAMPAIGN_OFFSET_XN * 1000 + 1 ---@type number integer constant
bj_MISSION_INDEX_XN02 = bj_CAMPAIGN_OFFSET_XN * 1000 + 2 ---@type number integer constant
bj_MISSION_INDEX_XN03 = bj_CAMPAIGN_OFFSET_XN * 1000 + 3 ---@type number integer constant
bj_MISSION_INDEX_XN04 = bj_CAMPAIGN_OFFSET_XN * 1000 + 4 ---@type number integer constant
bj_MISSION_INDEX_XN05 = bj_CAMPAIGN_OFFSET_XN * 1000 + 5 ---@type number integer constant
bj_MISSION_INDEX_XN06 = bj_CAMPAIGN_OFFSET_XN * 1000 + 6 ---@type number integer constant
bj_MISSION_INDEX_XN07 = bj_CAMPAIGN_OFFSET_XN * 1000 + 7 ---@type number integer constant
bj_MISSION_INDEX_XN08 = bj_CAMPAIGN_OFFSET_XN * 1000 + 8 ---@type number integer constant
bj_MISSION_INDEX_XN09 = bj_CAMPAIGN_OFFSET_XN * 1000 + 9 ---@type number integer constant
bj_MISSION_INDEX_XN10 = bj_CAMPAIGN_OFFSET_XN * 1000 + 10 ---@type number integer constant
bj_MISSION_INDEX_XH00 = bj_CAMPAIGN_OFFSET_XH * 1000 + 0 ---@type number integer constant
bj_MISSION_INDEX_XH01 = bj_CAMPAIGN_OFFSET_XH * 1000 + 1 ---@type number integer constant
bj_MISSION_INDEX_XH02 = bj_CAMPAIGN_OFFSET_XH * 1000 + 2 ---@type number integer constant
bj_MISSION_INDEX_XH03 = bj_CAMPAIGN_OFFSET_XH * 1000 + 3 ---@type number integer constant
bj_MISSION_INDEX_XH04 = bj_CAMPAIGN_OFFSET_XH * 1000 + 4 ---@type number integer constant
bj_MISSION_INDEX_XH05 = bj_CAMPAIGN_OFFSET_XH * 1000 + 5 ---@type number integer constant
bj_MISSION_INDEX_XH06 = bj_CAMPAIGN_OFFSET_XH * 1000 + 6 ---@type number integer constant
bj_MISSION_INDEX_XH07 = bj_CAMPAIGN_OFFSET_XH * 1000 + 7 ---@type number integer constant
bj_MISSION_INDEX_XH08 = bj_CAMPAIGN_OFFSET_XH * 1000 + 8 ---@type number integer constant
bj_MISSION_INDEX_XH09 = bj_CAMPAIGN_OFFSET_XH * 1000 + 9 ---@type number integer constant
bj_MISSION_INDEX_XU00 = bj_CAMPAIGN_OFFSET_XU * 1000 + 0 ---@type number integer constant
bj_MISSION_INDEX_XU01 = bj_CAMPAIGN_OFFSET_XU * 1000 + 1 ---@type number integer constant
bj_MISSION_INDEX_XU02 = bj_CAMPAIGN_OFFSET_XU * 1000 + 2 ---@type number integer constant
bj_MISSION_INDEX_XU03 = bj_CAMPAIGN_OFFSET_XU * 1000 + 3 ---@type number integer constant
bj_MISSION_INDEX_XU04 = bj_CAMPAIGN_OFFSET_XU * 1000 + 4 ---@type number integer constant
bj_MISSION_INDEX_XU05 = bj_CAMPAIGN_OFFSET_XU * 1000 + 5 ---@type number integer constant
bj_MISSION_INDEX_XU06 = bj_CAMPAIGN_OFFSET_XU * 1000 + 6 ---@type number integer constant
bj_MISSION_INDEX_XU07 = bj_CAMPAIGN_OFFSET_XU * 1000 + 7 ---@type number integer constant
bj_MISSION_INDEX_XU08 = bj_CAMPAIGN_OFFSET_XU * 1000 + 8 ---@type number integer constant
bj_MISSION_INDEX_XU09 = bj_CAMPAIGN_OFFSET_XU * 1000 + 9 ---@type number integer constant
bj_MISSION_INDEX_XU10 = bj_CAMPAIGN_OFFSET_XU * 1000 + 10 ---@type number integer constant
bj_MISSION_INDEX_XU11 = bj_CAMPAIGN_OFFSET_XU * 1000 + 11 ---@type number integer constant
bj_MISSION_INDEX_XU12 = bj_CAMPAIGN_OFFSET_XU * 1000 + 12 ---@type number integer constant
bj_MISSION_INDEX_XU13 = bj_CAMPAIGN_OFFSET_XU * 1000 + 13 ---@type number integer constant
bj_MISSION_INDEX_XO00 = bj_CAMPAIGN_OFFSET_XO * 1000 + 0 ---@type number integer constant
bj_CINEMATICINDEX_TOP = 0 ---@type number integer constant
bj_CINEMATICINDEX_HOP = 1 ---@type number integer constant
bj_CINEMATICINDEX_HED = 2 ---@type number integer constant
bj_CINEMATICINDEX_OOP = 3 ---@type number integer constant
bj_CINEMATICINDEX_OED = 4 ---@type number integer constant
bj_CINEMATICINDEX_UOP = 5 ---@type number integer constant
bj_CINEMATICINDEX_UED = 6 ---@type number integer constant
bj_CINEMATICINDEX_NOP = 7 ---@type number integer constant
bj_CINEMATICINDEX_NED = 8 ---@type number integer constant
bj_CINEMATICINDEX_XOP = 9 ---@type number integer constant
bj_CINEMATICINDEX_XED = 10 ---@type number integer constant
bj_ALLIANCE_UNALLIED = 0 ---@type number integer constant
bj_ALLIANCE_UNALLIED_VISION = 1 ---@type number integer constant
bj_ALLIANCE_ALLIED = 2 ---@type number integer constant
bj_ALLIANCE_ALLIED_VISION = 3 ---@type number integer constant
bj_ALLIANCE_ALLIED_UNITS = 4 ---@type number integer constant
bj_ALLIANCE_ALLIED_ADVUNITS = 5 ---@type number integer constant
bj_ALLIANCE_NEUTRAL = 6 ---@type number integer constant
bj_ALLIANCE_NEUTRAL_VISION = 7 ---@type number integer constant
bj_KEYEVENTTYPE_DEPRESS = 0 ---@type number integer constant
bj_KEYEVENTTYPE_RELEASE = 1 ---@type number integer constant
bj_KEYEVENTKEY_LEFT = 0 ---@type number integer constant
bj_KEYEVENTKEY_RIGHT = 1 ---@type number integer constant
bj_KEYEVENTKEY_DOWN = 2 ---@type number integer constant
bj_KEYEVENTKEY_UP = 3 ---@type number integer constant
bj_TIMETYPE_ADD = 0 ---@type number integer constant
bj_TIMETYPE_SET = 1 ---@type number integer constant
bj_TIMETYPE_SUB = 2 ---@type number integer constant
bj_CAMERABOUNDS_ADJUST_ADD = 0 ---@type number integer constant
bj_CAMERABOUNDS_ADJUST_SUB = 1 ---@type number integer constant
bj_QUESTTYPE_REQ_DISCOVERED = 0 ---@type number integer constant
bj_QUESTTYPE_REQ_UNDISCOVERED = 1 ---@type number integer constant
bj_QUESTTYPE_OPT_DISCOVERED = 2 ---@type number integer constant
bj_QUESTTYPE_OPT_UNDISCOVERED = 3 ---@type number integer constant
bj_QUESTMESSAGE_DISCOVERED = 0 ---@type number integer constant
bj_QUESTMESSAGE_UPDATED = 1 ---@type number integer constant
bj_QUESTMESSAGE_COMPLETED = 2 ---@type number integer constant
bj_QUESTMESSAGE_FAILED = 3 ---@type number integer constant
bj_QUESTMESSAGE_REQUIREMENT = 4 ---@type number integer constant
bj_QUESTMESSAGE_MISSIONFAILED = 5 ---@type number integer constant
bj_QUESTMESSAGE_ALWAYSHINT = 6 ---@type number integer constant
bj_QUESTMESSAGE_HINT = 7 ---@type number integer constant
bj_QUESTMESSAGE_SECRET = 8 ---@type number integer constant
bj_QUESTMESSAGE_UNITACQUIRED = 9 ---@type number integer constant
bj_QUESTMESSAGE_UNITAVAILABLE = 10 ---@type number integer constant
bj_QUESTMESSAGE_ITEMACQUIRED = 11 ---@type number integer constant
bj_QUESTMESSAGE_WARNING = 12 ---@type number integer constant
bj_SORTTYPE_SORTBYVALUE = 0 ---@type number integer constant
bj_SORTTYPE_SORTBYPLAYER = 1 ---@type number integer constant
bj_SORTTYPE_SORTBYLABEL = 2 ---@type number integer constant
bj_CINEFADETYPE_FADEIN = 0 ---@type number integer constant
bj_CINEFADETYPE_FADEOUT = 1 ---@type number integer constant
bj_CINEFADETYPE_FADEOUTIN = 2 ---@type number integer constant
bj_REMOVEBUFFS_POSITIVE = 0 ---@type number integer constant
bj_REMOVEBUFFS_NEGATIVE = 1 ---@type number integer constant
bj_REMOVEBUFFS_ALL = 2 ---@type number integer constant
bj_REMOVEBUFFS_NONTLIFE = 3 ---@type number integer constant
bj_BUFF_POLARITY_POSITIVE = 0 ---@type number integer constant
bj_BUFF_POLARITY_NEGATIVE = 1 ---@type number integer constant
bj_BUFF_POLARITY_EITHER = 2 ---@type number integer constant
bj_BUFF_RESIST_MAGIC = 0 ---@type number integer constant
bj_BUFF_RESIST_PHYSICAL = 1 ---@type number integer constant
bj_BUFF_RESIST_EITHER = 2 ---@type number integer constant
bj_BUFF_RESIST_BOTH = 3 ---@type number integer constant
bj_HEROSTAT_STR = 0 ---@type number integer constant
bj_HEROSTAT_AGI = 1 ---@type number integer constant
bj_HEROSTAT_INT = 2 ---@type number integer constant
bj_MODIFYMETHOD_ADD = 0 ---@type number integer constant
bj_MODIFYMETHOD_SUB = 1 ---@type number integer constant
bj_MODIFYMETHOD_SET = 2 ---@type number integer constant
bj_UNIT_STATE_METHOD_ABSOLUTE = 0 ---@type number integer constant
bj_UNIT_STATE_METHOD_RELATIVE = 1 ---@type number integer constant
bj_UNIT_STATE_METHOD_DEFAULTS = 2 ---@type number integer constant
bj_UNIT_STATE_METHOD_MAXIMUM = 3 ---@type number integer constant
bj_GATEOPERATION_CLOSE = 0 ---@type number integer constant
bj_GATEOPERATION_OPEN = 1 ---@type number integer constant
bj_GATEOPERATION_DESTROY = 2 ---@type number integer constant
bj_GAMECACHE_BOOLEAN = 0 ---@type number integer constant
bj_GAMECACHE_INTEGER = 1 ---@type number integer constant
bj_GAMECACHE_REAL = 2 ---@type number integer constant
bj_GAMECACHE_UNIT = 3 ---@type number integer constant
bj_GAMECACHE_STRING = 4 ---@type number integer constant
bj_HASHTABLE_BOOLEAN = 0 ---@type number integer constant
bj_HASHTABLE_INTEGER = 1 ---@type number integer constant
bj_HASHTABLE_REAL = 2 ---@type number integer constant
bj_HASHTABLE_STRING = 3 ---@type number integer constant
bj_HASHTABLE_HANDLE = 4 ---@type number integer constant
bj_ITEM_STATUS_HIDDEN = 0 ---@type number integer constant
bj_ITEM_STATUS_OWNED = 1 ---@type number integer constant
bj_ITEM_STATUS_INVULNERABLE = 2 ---@type number integer constant
bj_ITEM_STATUS_POWERUP = 3 ---@type number integer constant
bj_ITEM_STATUS_SELLABLE = 4 ---@type number integer constant
bj_ITEM_STATUS_PAWNABLE = 5 ---@type number integer constant
bj_ITEMCODE_STATUS_POWERUP = 0 ---@type number integer constant
bj_ITEMCODE_STATUS_SELLABLE = 1 ---@type number integer constant
bj_ITEMCODE_STATUS_PAWNABLE = 2 ---@type number integer constant
bj_MINIMAPPINGSTYLE_SIMPLE = 0 ---@type number integer constant
bj_MINIMAPPINGSTYLE_FLASHY = 1 ---@type number integer constant
bj_MINIMAPPINGSTYLE_ATTACK = 2 ---@type number integer constant
bj_CORPSE_MAX_DEATH_TIME = 8.00 ---@type number real constant
bj_CORPSETYPE_FLESH = 0 ---@type number integer constant
bj_CORPSETYPE_BONE = 1 ---@type number integer constant
bj_ELEVATOR_BLOCKER_CODE = 'DTep' ---@type number integer constant
bj_ELEVATOR_CODE01 = 'DTrf' ---@type number integer constant
bj_ELEVATOR_CODE02 = 'DTrx' ---@type number integer constant
bj_ELEVATOR_WALL_TYPE_ALL = 0 ---@type number integer constant
bj_ELEVATOR_WALL_TYPE_EAST = 1 ---@type number integer constant
bj_ELEVATOR_WALL_TYPE_NORTH = 2 ---@type number integer constant
bj_ELEVATOR_WALL_TYPE_SOUTH = 3 ---@type number integer constant
bj_ELEVATOR_WALL_TYPE_WEST = 4 ---@type number integer constant
bj_FORCE_PLAYER = {} ---@type force
bj_MELEE_MAX_TWINKED_HEROES = 0 ---@type number integer
bj_forLoopAIndex = 0 ---@type number integer
bj_forLoopBIndex = 0 ---@type number integer
bj_forLoopAIndexEnd = 0 ---@type number integer
bj_forLoopBIndexEnd = 0 ---@type number integer
bj_slotControlReady = false ---@type boolean
bj_slotControlUsed = {} ---@type boolean[]
bj_slotControl = {} ---@type mapcontrol
bj_gameStarted = false ---@type boolean
bj_volumeGroupsTimer = CreateTimer() ---@type timer
bj_isSinglePlayer = false ---@type boolean
bj_useDawnDuskSounds = true ---@type boolean
bj_dncIsDaytime = false ---@type boolean
bj_stockAllowedPermanent = {} ---@type boolean[]
bj_stockAllowedCharged = {} ---@type boolean[]
bj_stockAllowedArtifact = {} ---@type boolean[]
bj_stockPickedItemLevel = 0 ---@type number integer
bj_stockPickedItemType = nil ---@type itemtype
bj_meleeVisibilityIsDay = true ---@type boolean
bj_meleeGrantHeroItems = false ---@type boolean
bj_meleeNearestMineDist = 0.00 ---@type number real
bj_meleeGameOver = false ---@type boolean
bj_meleeDefeated = {} ---@type boolean[]
bj_meleeVictoried = {} ---@type boolean[]
bj_ghoul = {} ---@type unit
bj_crippledTimer = {} ---@type timer
bj_crippledTimerWindows = {} ---@type timerdialog
bj_playerIsCrippled = {} ---@type boolean[]
bj_playerIsExposed = {} ---@type boolean[]
bj_finishSoonAllExposed = false ---@type boolean
bj_meleeTwinkedHeroes = {} ---@type number[] integer
bj_rescueChangeColorUnit = true ---@type boolean
bj_rescueChangeColorBldg = true ---@type boolean
bj_cineModePriorSpeed = MAP_SPEED_NORMAL ---@type gamespeed
bj_cineModePriorFogSetting = false ---@type boolean
bj_cineModePriorMaskSetting = false ---@type boolean
bj_cineModeAlreadyIn = false ---@type boolean
bj_cineModePriorDawnDusk = false ---@type boolean
bj_cineModeSavedSeed = 0 ---@type number integer
bj_cineFadeContinueRed = 0 ---@type number real
bj_cineFadeContinueGreen = 0 ---@type number real
bj_cineFadeContinueBlue = 0 ---@type number real
bj_cineFadeContinueTrans = 0 ---@type number real
bj_cineFadeContinueDuration = 0 ---@type number real
bj_cineFadeContinueTex = "" ---@type string
bj_queuedExecTotal = 0 ---@type number integer
bj_queuedExecTriggers = {} ---@type trigger
bj_queuedExecUseConds = {} ---@type boolean[]
bj_queuedExecTimeoutTimer = CreateTimer() ---@type timer
bj_destInRegionDiesCount = 0 ---@type number integer
bj_groupCountUnits = 0 ---@type number integer
bj_forceCountPlayers = 0 ---@type number integer
bj_groupEnumTypeId = 0 ---@type number integer
bj_groupRandomConsidered = 0 ---@type number integer
bj_randomSubGroupWant = 0 ---@type number integer
bj_randomSubGroupTotal = 0 ---@type number integer
bj_randomSubGroupChance = 0 ---@type number real
bj_destRandomConsidered = 0 ---@type number integer
bj_itemRandomConsidered = 0 ---@type number integer
bj_forceRandomConsidered = 0 ---@type number integer
bj_makeUnitRescuableFlag = true ---@type boolean
bj_pauseAllUnitsFlag = true ---@type boolean
bj_enumDestructableRadius = 0 ---@type number real
bj_isUnitGroupDeadResult = true ---@type boolean
bj_isUnitGroupEmptyResult = true ---@type boolean
bj_isUnitGroupInRectResult = true ---@type boolean
bj_changeLevelShowScores = false ---@type boolean
bj_suspendDecayFleshGroup = CreateGroup() ---@type group
bj_suspendDecayBoneGroup = CreateGroup() ---@type group
bj_delayedSuspendDecayTimer = CreateTimer() ---@type timer
bj_livingPlayerUnitsTypeId = 0 ---@type number integer
bj_randDistCount = 0 ---@type number integer
bj_randDistID = {} ---@type number[] integer
bj_randDistChance = {} ---@type number[] integer
bj_lastCreatedGroup = CreateGroup() ---@type group
bj_lastStartedTimer = CreateTimer() ---@type timer
bj_lastPlayedMusic = "" ---@type string
bj_lastTransmissionDuration = 0 ---@type number real
bj_wantDestroyGroup = false ---@type boolean

