---@class handle
---@class agent:handle
---@class event:agent
---@class player:agent
---@class widget:agent
---@class unit:widget
---@class destructable:widget
---@class item:widget
---@class ability:agent
---@class buff:ability
---@class force:agent
---@class group:agent
---@class trigger:agent
---@class triggercondition:agent
---@class triggeraction:handle
---@class timer:agent
---@class location:agent
---@class region:agent
---@class rect:agent
---@class boolexpr:agent
---@class sound:agent
---@class conditionfunc:boolexpr
---@class filterfunc:boolexpr
---@class unitpool:handle
---@class itempool:handle
---@class race:handle
---@class alliancetype:handle
---@class racepreference:handle
---@class gamestate:handle
---@class igamestate:gamestate
---@class fgamestate:gamestate
---@class playerstate:handle
---@class playerscore:handle
---@class playergameresult:handle
---@class unitstate:handle
---@class aidifficulty:handle
---@class eventid:handle
---@class gameevent:eventid
---@class playerevent:eventid
---@class playerunitevent:eventid
---@class unitevent:eventid
---@class limitop:eventid
---@class widgetevent:eventid
---@class dialogevent:eventid
---@class unittype:handle
---@class gamespeed:handle
---@class gamedifficulty:handle
---@class gametype:handle
---@class mapflag:handle
---@class mapvisibility:handle
---@class mapsetting:handle
---@class mapdensity:handle
---@class mapcontrol:handle
---@class playerslotstate:handle
---@class volumegroup:handle
---@class camerafield:handle
---@class camerasetup:handle
---@class playercolor:handle
---@class placement:handle
---@class startlocprio:handle
---@class raritycontrol:handle
---@class blendmode:handle
---@class texmapflags:handle
---@class effect:agent
---@class effecttype:handle
---@class weathereffect:handle
---@class terraindeformation:handle
---@class fogstate:handle
---@class fogmodifier:agent
---@class dialog:agent
---@class button:agent
---@class quest:agent
---@class questitem:agent
---@class defeatcondition:agent
---@class timerdialog:agent
---@class leaderboard:agent
---@class multiboard:agent
---@class multiboarditem:agent
---@class trackable:agent
---@class gamecache:agent
---@class version:handle
---@class itemtype:handle
---@class texttag:handle
---@class attacktype:handle
---@class damagetype:handle
---@class weapontype:handle
---@class soundtype:handle
---@class lightning:handle
---@class pathingtype:handle
---@class image:handle
---@class ubersplat:handle
---@class hashtable:agent

---@type string
s = 1 + 2 .. ""

--- constant
---@type number real
a = 1. + 2 * 3

---@type number real
d = nil

---@type number[] integer
l__Array = {}

